# Generated by Django 5.1 on 2026-07-02 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0002_alter_purchase_options_purchase_line_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره استعلام')),
                ('inquiry_date', models.CharField(max_length=20, verbose_name='تاریخ استعلام')),
                ('deadline', models.CharField(blank=True, max_length=20, verbose_name='مهلت استعلام')),
                ('purchase_type', models.CharField(blank=True, max_length=50, verbose_name='نوع خرید')),
                ('urgency_code', models.CharField(blank=True, max_length=50, verbose_name='رمز فوریت')),
                ('supply_unit', models.CharField(blank=True, max_length=100, verbose_name='واحد/رمز تامین')),
                ('reason', models.TextField(blank=True, verbose_name='علت خرید')),
                ('warehouse', models.CharField(blank=True, max_length=100, verbose_name='انبار')),
                ('requester', models.CharField(blank=True, max_length=100, verbose_name='درخواست دهنده')),
                ('risk_note', models.TextField(blank=True, verbose_name='ریسک عدم خرید')),
                ('expert_name', models.CharField(blank=True, max_length=100, verbose_name='کارشناس خرید')),
                ('issuer', models.CharField(blank=True, max_length=100, verbose_name='صادر کننده سند')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادر شده'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], db_index=True, default='issued', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='purchases.purchase', verbose_name='درخواست خرید')),
            ],
            options={
                'verbose_name': 'استعلام',
                'verbose_name_plural': 'استعلام\u200cها',
                'db_table': 'inquiries',
                'ordering': ['-inquiry_number'],
                'indexes': [models.Index(fields=['inquiry_number'], name='inquiries_inquiry_b75fc1_idx'), models.Index(fields=['purchase'], name='inquiries_purchas_f758b9_idx'), models.Index(fields=['expert_name'], name='inquiries_expert__bb0e54_idx'), models.Index(fields=['status'], name='inquiries_status_a769b4_idx')],
            },
        ),
    ]
