# Generated by Django 5.1 on 2026-07-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(max_length=200, verbose_name='پیمانکار')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='شماره پیش\u200cفاکتور')),
                ('invoice_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ پیش\u200cفاکتور')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('validity_days', models.IntegerField(default=7, verbose_name='اعتبار (روز)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد مالیات')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='تخفیف')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_selected', models.BooleanField(default=False, verbose_name='انتخاب شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_invoices', to='inquiries.inquiry', verbose_name='استعلام')),
            ],
            options={
                'verbose_name': 'پیش\u200cفاکتور',
                'verbose_name_plural': 'پیش\u200cفاکتورها',
                'db_table': 'pre_invoices',
            },
        ),
        migrations.CreateModel(
            name='PreInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(default=1, verbose_name='ردیف')),
                ('product_title', models.CharField(max_length=255, verbose_name='عنوان کالا')),
                ('product_code', models.CharField(blank=True, max_length=50, verbose_name='کد کالا')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعداد')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='فی واحد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('pre_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inquiries.preinvoice', verbose_name='پیش\u200cفاکتور')),
            ],
            options={
                'verbose_name': 'قلم پیش\u200cفاکتور',
                'verbose_name_plural': 'اقلام پیش\u200cفاکتور',
                'db_table': 'pre_invoice_lines',
            },
        ),
    ]
