# Generated by Django 5.1 on 2026-07-02 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره درخواست خرید')),
                ('base_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره درخواست کالا')),
                ('request_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ درخواست کالا')),
                ('purchase_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ درخواست')),
                ('supply_unit', models.CharField(blank=True, max_length=100, verbose_name='واحد تامین')),
                ('requester', models.CharField(blank=True, max_length=100, verbose_name='درخواست کننده')),
                ('product_code', models.CharField(blank=True, max_length=50, verbose_name='کد قلم خریدنی')),
                ('product_title', models.CharField(blank=True, max_length=255, verbose_name='نام قلم خریدنی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد سنجش')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار درخواست')),
                ('expert_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='نام کارشناس خرید')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات درخواست خرید')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='وضعیت درخواست خرید')),
                ('required_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ نیاز درخواست خرید')),
                ('inquiry_deadline', models.CharField(blank=True, max_length=20, verbose_name='مهلت استعلام')),
                ('inquiry_deadline_2', models.CharField(blank=True, max_length=20, verbose_name='مهلت استعلام 2')),
                ('inquiry_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='شماره استعلام')),
                ('inquiry_received_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ دریافت درخواست')),
                ('purchase_type', models.CharField(blank=True, max_length=50, verbose_name='روند خرید')),
                ('preinvoice_number', models.CharField(blank=True, max_length=50, verbose_name='شماره پیش فاکتور')),
                ('preinvoice_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='فی پیش فاکتور')),
                ('preinvoice_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع پیش فاکتور بدون ارزش افزوده')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='شماره دستور خرید')),
                ('order_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ دستور خرید')),
                ('order_request_number', models.CharField(blank=True, max_length=50, verbose_name='شماره سفارش')),
                ('order_request_status', models.CharField(blank=True, max_length=50, verbose_name='وضعیت سفارش')),
                ('order_request_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ سفارش')),
                ('order_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع کل سفارش')),
                ('advance_payment', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ پیش پرداخت')),
                ('deductions', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کسور')),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار تحویل')),
                ('delivery_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='شماره تحویل')),
                ('delivery_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ تحویل')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='تامین کننده')),
                ('invoice_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='فی فاکتور')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='شماره فاکتور')),
                ('invoice_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع کل فاکتور')),
                ('payment_request_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ درخواست پرداخت')),
                ('payment_request_number', models.CharField(blank=True, max_length=50, verbose_name='شماره درخواست پرداخت')),
                ('payment_registration_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ ثبت واریزی')),
                ('payment_completion_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ انجام واریزی')),
                ('current_status', models.CharField(choices=[('waiting_inquiry', 'در انتظار استعلام'), ('inquiry_issued', 'استعلام صادر شده'), ('order_issued', 'دستور خرید صادر شده'), ('order_placed', 'سفارش صادر شده'), ('waiting_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('delivered', 'تحویل شده')], db_index=True, default='waiting_inquiry', max_length=50, verbose_name='وضعیت فعلی خرید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='وارد کننده')),
            ],
            options={
                'verbose_name': 'درخواست خرید',
                'verbose_name_plural': 'درخواست\u200cهای خرید',
                'db_table': 'purchases',
                'ordering': ['-purchase_number'],
                'indexes': [models.Index(fields=['purchase_number', 'current_status'], name='purchases_purchas_d0f1e5_idx'), models.Index(fields=['expert_name', 'status'], name='purchases_expert__67ac52_idx'), models.Index(fields=['product_code'], name='purchases_product_b6404b_idx'), models.Index(fields=['inquiry_number'], name='purchases_inquiry_9445bd_idx'), models.Index(fields=['order_number'], name='purchases_order_n_fa1fbd_idx'), models.Index(fields=['delivery_number'], name='purchases_deliver_1df195_idx')],
            },
        ),
    ]
