# Generated by Django 5.1 on 2026-07-02 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_number', 'line_number'], 'verbose_name': 'درخواست خرید', 'verbose_name_plural': 'درخواست\u200cهای خرید'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='line_number',
            field=models.IntegerField(default=1, help_text='شماره ردیف در فایل اکسل', verbose_name='شماره خط در اکسل'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_number',
            field=models.CharField(db_index=True, max_length=50, verbose_name='شماره درخواست خرید'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('purchase_number', 'line_number'), name='unique_purchase_line'),
        ),
    ]
