# Generated by Django 5.1 on 2026-07-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_options_purchase_line_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_registration_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='تاریخ ثبت واریزی'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_request_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره درخواست پرداخت'),
        ),
    ]
