# Generated by Django 5.1 on 2026-07-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='expert_name',
            field=models.CharField(blank=True, help_text='فقط برای نقش کارشناس - نامی که در گزارش\u200cها نمایش داده می\u200cشود', max_length=100, verbose_name='نام کارشناس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'سوپر یوزر'), ('admin', 'مدیر تدارکات'), ('expert', 'کارشناس تدارکات'), ('warehouse', 'انباردار')], db_index=True, default='expert', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='warehouse',
            field=models.CharField(blank=True, help_text='فقط برای نقش انباردار - انبار مسئول', max_length=100, verbose_name='انبار'),
        ),
    ]
