# Generated by Django 5.1 on 2026-07-02 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('login', 'ورود'), ('logout', 'خروج'), ('export', 'خروجی'), ('issue', 'صدور'), ('advance', 'پیشبرد')], max_length=20, verbose_name='نوع عملیات')),
                ('entity_type', models.CharField(max_length=50, verbose_name='نوع موجودیت')),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه موجودیت')),
                ('entity_repr', models.CharField(blank=True, max_length=255, verbose_name='نمایش موجودیت')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='فیلد')),
                ('old_value', models.TextField(blank=True, verbose_name='مقدار قبلی')),
                ('new_value', models.TextField(blank=True, verbose_name='مقدار جدید')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ تغییرات',
                'verbose_name_plural': 'لاگ\u200cهای تغییرات',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_logs_created_43fcd6_idx'), models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx')],
            },
        ),
    ]
