# Generated by Django 5.1 on 2026-07-02 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0001_initial'),
        ('purchases', '0002_alter_purchase_options_purchase_line_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره دستور')),
                ('product_title', models.CharField(max_length=255, verbose_name='عنوان کالا')),
                ('product_code', models.CharField(blank=True, max_length=50, verbose_name='کد کالا')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعداد')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='فی واحد')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع کل')),
                ('contractor', models.CharField(blank=True, max_length=200, verbose_name='تامین کننده / پیمانکار')),
                ('warehouse', models.CharField(blank=True, max_length=100, verbose_name='انبار مقصد')),
                ('expert_name', models.CharField(blank=True, max_length=100, verbose_name='کارشناس مسئول')),
                ('stage', models.CharField(choices=[('order_issued', 'صدور دستور'), ('order_placed', 'ثبت سفارش'), ('payment', 'پرداخت'), ('delivered', 'تحویل شده')], db_index=True, default='order_issued', max_length=20, verbose_name='مرحله فعلی')),
                ('status', models.CharField(default='جاری', max_length=50, verbose_name='وضعیت')),
                ('order_date', models.CharField(max_length=20, verbose_name='تاریخ صدور دستور')),
                ('order_request_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ ثبت سفارش')),
                ('order_request_number', models.CharField(blank=True, max_length=50, verbose_name='شماره سفارش')),
                ('payment_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ پرداخت')),
                ('payment_number', models.CharField(blank=True, max_length=50, verbose_name='شماره پرداخت')),
                ('delivery_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ تحویل')),
                ('delivery_number', models.CharField(blank=True, max_length=50, verbose_name='شماره تحویل / مجوز ورود')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('issued_by', models.CharField(blank=True, max_length=100, verbose_name='صادر کننده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inquiries.inquiry', verbose_name='استعلام مرتبط')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='purchases.purchase', verbose_name='درخواست خرید')),
            ],
            options={
                'verbose_name': 'دستور خرید',
                'verbose_name_plural': 'دستورات خرید',
                'db_table': 'orders',
                'ordering': ['-order_number'],
                'indexes': [models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'), models.Index(fields=['stage'], name='orders_stage_89c939_idx'), models.Index(fields=['purchase'], name='orders_purchas_a93e08_idx'), models.Index(fields=['contractor'], name='orders_contrac_ae7fa7_idx')],
            },
        ),
    ]
