# Generated by Django 5.1 on 2026-07-02 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('type', models.CharField(choices=[('info', 'اطلاعیه'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('inquiry', 'استعلام جدید'), ('order', 'دستور خرید'), ('delivery', 'تحویل کالا')], default='info', max_length=20, verbose_name='نوع')),
                ('reference_url', models.CharField(blank=True, max_length=500, verbose_name='لینک مرجع')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
