# Generated by Django 5.1 on 2026-07-02 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره تحویل / مجوز ورود')),
                ('product_title', models.CharField(max_length=255, verbose_name='عنوان کالا')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار تحویلی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد')),
                ('warehouse', models.CharField(blank=True, max_length=100, verbose_name='انبار مقصد')),
                ('receiver', models.CharField(blank=True, max_length=100, verbose_name='تحویل گیرنده')),
                ('delivery_date', models.CharField(max_length=20, verbose_name='تاریخ تحویل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات انباردار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order', verbose_name='دستور خرید')),
            ],
            options={
                'verbose_name': 'تحویل',
                'verbose_name_plural': 'تحویل\u200cها',
                'db_table': 'deliveries',
                'ordering': ['-delivery_date', '-pk'],
            },
        ),
    ]
