# Generated by Django 5.1 on 2026-07-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('orders', '0001_initial'),
        ('purchases', '0002_alter_purchase_options_purchase_line_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='purchases.purchase', verbose_name='درخواست خرید'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, verbose_name='تامین کننده'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order', verbose_name='دستور خرید'),
        ),
    ]
